source 'https://rubygems.org'

gem 'zeitwerk'
gem 'value_semantics'
gem 'nokogiri'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rouge'
gem 'byebug'
gem 'test_bench'
gem 'rubocop'
gem 'dry-inflector'
gem 'memery'
gem 'addressable'
gem 'pry'
gem 'dry-cli'
gem 'base64'
gem 'bigdecimal'

# dev server
gem 'thin'
gem 'hanami-controller', github: 'hanami/controller', branch: 'main'
gem 'rerun'
gem 'better_errors'
gem 'binding_of_caller'

