source 'https://rubygems.org'

gem 'zeitwerk'
gem 'value_semantics'
gem 'nokogiri'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rouge'
gem 'byebug'
gem 'test_bench'
gem 'rubocop'
gem 'dry-inflector'
gem 'memery'
